Problems Set 3
========================================================


### Diamonds Data


```{r}
library(ggplot2)
data(diamonds)

# observations, variables, number of ordered factors
str(diamonds)
levels(diamonds$color)
```

### Price Histogram

```{r}
qplot(x = price, data = diamonds)

```

### Price Histogram Summary

```{r}
summary(diamonds$price)
```

### Diamond Count

```{r}
sum(diamonds$price < 500)
sum(diamonds$price < 250)
sum(diamonds$price >= 15000)
```

### Cheaper Diamonds

```{r}
# Explore the largest peak in the
# price histogram you created earlier
qplot(x = price, data = diamonds, binwidth = 50, color = I('black'), fill = I('#5760AB')) + 
  scale_x_continuous(limits = c(300, 1500), breaks = seq(300, 1500, 100))
```


### Price by Cut Histogram

```{r}
# Break out the histogram of diamond prices by cut

qplot(x = price, data = diamonds, color = I('black'), 
fill = I('#5760AB'), binwidth = 1000) + 
  scale_x_continuous(limits = c(326, 18820), breaks = seq(326, 18820, 1000)) +
  facet_wrap(~cut, ncol = 2)
```

### Price by Cut

```{r}
by(diamonds$price, diamonds$cut, max)
```

### Scales and Multiple Histograms

```{r}
qplot(x = price, data = diamonds) + facet_wrap(~ cut, scales = 'free_y')
```

### Price per Carat by Cut

```{r}
# Adjust the bin width and transform the scale
# of the x-axis using log10
qplot(x = price/carat, data = diamonds, binwidth = 0.05) + 
  scale_x_log10() +
  facet_wrap(~cut, scales = 'free_y')
```

### Price Box Plots

```{r}
# Investigate the price of diamonds using box plots,
# numerical summaries, and one of the following categorical
# variables: cut, clarity, or color
qplot(x = cut, y = price, data = diamonds, geom = 'boxplot') + 
  coord_cartesian(ylim = c(0, 7000))
by(diamonds$price, diamonds$cut, summary)
```

### Interquartile Range(IQR)

```{r}
# IQR for the best color
IQR(subset(diamonds, color == 'D')$price)
# IQR for the worst color
IQR(subset(diamonds, color == 'J')$price)
```

### Price per Carate Box Plots by Color

```{r}
qplot(x = color, y = price/carat, data = diamonds, geom = 'boxplot', fill = color) +
  coord_cartesian(ylim = c(0, 15000))
```

#### Carat Frequency Polygon

```{r}
qplot(x = carat, data = diamonds, geom = 'freqpoly', binwidth = 0.1) +
  scale_x_continuous(limits = c(0, 5), breaks = seq(0, 5, 0.1)) + 
  scale_y_continuous(breaks = seq(0, 12000, 2000))
```

### Gapminder Data

```{r}
# The Gapminder website contains over 500 data sets with information about
# the world's population. Your task is to download a data set of your choice
# and create 2-5 plots that make use of the techniques from Lesson 3.

# You might use a simple histogram, a boxplot split over a categorical variable,
# or a frequency polygon. The choice is yours!
library(xlsx)
library(rJava)
bmi_fe <- read.xlsx('indicator_BMI female ASM.xlsx', 1)

qplot(x = X2008, data = bmi_fe, color = I('black'), fill = I('#099DD9'), 
      binwidth = 1, xlab = 'Avg Female BMI in 2008', 
      ylab = 'Number of Countries')
qplot(x = X2008, data = bmi_fe, geom = 'freqpoly')
```

### Exploring Your Friends' Birthdays


```{r}
# Your task is to investigate the distribution of your friends'
# birth months and days.

# Here some questions you could answer, and we hope you think of others.

# **********************************************************************

# How many people share your birthday? Do you know them?
# (Reserve time with them or save money to buy them a gift!)

# Which month contains the most number of birthdays?

# How many birthdays are in each month?

# Which day of the year has the most number of birthdays?

# Do you have at least 365 friends that have birthdays on everyday
# of the year?

library(ggplot2)
library(lubridate)
library(reshape2)

birthday <- read.csv('birthdaysExample.csv')
birthday$dates <- as.Date(birthday$dates,format = "%m/%d/%y")
birthday$day <- format((as.Date(birthday$dates, format = "%m/%d/%y")), format="%d")
birthday$month <- format((as.Date(birthday$dates, format = "%m/%d/%y")), format = "%m")
birthday$year <- format((as.Date(birthday$dates, format = "%m/%d/%y")), format = "%y")

birthday$same_bday <- ifelse(birthday$day==24 & birthday$month==8, 1, 0)
sum(birthday$same_day)

qplot(x = day, data = birthday, color = I('black'), fill = I('#5760AB'))
qplot(x = month, data = birthday, color = I('black'), fill = I('#099DD9'))
table(birthday$month)
```

